# Generated by Django 6.0.2 on 2026-03-10 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_flow', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HourlyPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('model_name', models.CharField(max_length=100)),
                ('predicted_price', models.FloatField()),
                ('current_price_at_prediction', models.FloatField(help_text='Price of the stock when the prediction was made')),
                ('actual_price', models.FloatField(blank=True, help_text='Actual price fetched on the next run', null=True)),
                ('absolute_error', models.FloatField(blank=True, null=True)),
                ('pct_error', models.FloatField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('predicted_at', models.DateTimeField(auto_now_add=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_predictions', to='ml_flow.pipelinerun')),
            ],
            options={
                'ordering': ['-predicted_at'],
            },
        ),
    ]
