# Generated by Codex on 2026-03-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("portfolios", "__first__"),
        ("ml_flow", "0002_hourlyprediction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForecastRequest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("prediction_scope", models.CharField(choices=[("single_stock", "Single Stock"), ("portfolio", "Portfolio")], max_length=20)),
                ("interval", models.CharField(default="1h", max_length=10)),
                ("training_days", models.IntegerField(default=30)),
                ("requested_tickers", models.JSONField(blank=True, default=list)),
                ("target_datetime", models.DateTimeField()),
                ("resolved_target_datetime", models.DateTimeField(blank=True, null=True)),
                ("requested_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("resolved", "Resolved"), ("partial", "Partial"), ("failed", "Failed"), ("expired", "Expired")], default="pending", max_length=20)),
                ("results_json", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True, null=True)),
                ("created_by", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="forecast_requests", to=settings.AUTH_USER_MODEL)),
                ("portfolio", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forecast_requests", to="portfolios.portfolio")),
            ],
            options={"ordering": ["-requested_at"]},
        ),
        migrations.CreateModel(
            name="ForecastPrediction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("ticker", models.CharField(max_length=20)),
                ("best_model", models.CharField(max_length=100)),
                ("current_price_at_request", models.FloatField()),
                ("predicted_price", models.FloatField()),
                ("model_predictions", models.JSONField(blank=True, default=dict)),
                ("model_metrics", models.JSONField(blank=True, default=dict)),
                ("actual_price", models.FloatField(blank=True, null=True)),
                ("actual_price_timestamp", models.DateTimeField(blank=True, null=True)),
                ("absolute_error", models.FloatField(blank=True, null=True)),
                ("pct_error", models.FloatField(blank=True, null=True)),
                ("direction_match", models.BooleanField(blank=True, null=True)),
                ("status", models.CharField(choices=[("pending", "Pending"), ("verified", "Verified"), ("expired", "Expired"), ("failed", "Failed")], default="pending", max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("forecast_request", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name="forecast_predictions", to="ml_flow.forecastrequest")),
            ],
            options={"ordering": ["-created_at"]},
        ),
    ]
