# Generated by Django 5.1 on 2026-03-15 17:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ml_flow', '0003_forecastrequest_forecastprediction'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pipelinerun',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('partial', 'Partial'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='SingleStockForecast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticker', models.CharField(max_length=20)),
                ('company_name', models.CharField(blank=True, max_length=255)),
                ('interval', models.CharField(default='1h', max_length=10)),
                ('training_days', models.IntegerField(default=30)),
                ('target_datetime', models.DateTimeField()),
                ('resolved_target_datetime', models.DateTimeField(blank=True, null=True)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('failed', 'Failed'), ('expired', 'Expired')], default='pending', max_length=20)),
                ('current_price', models.FloatField(blank=True, null=True)),
                ('predicted_price', models.FloatField(blank=True, null=True)),
                ('best_model', models.CharField(blank=True, max_length=100)),
                ('model_predictions', models.JSONField(blank=True, default=dict)),
                ('model_metrics', models.JSONField(blank=True, default=dict)),
                ('steps_ahead', models.IntegerField(default=1)),
                ('actual_price', models.FloatField(blank=True, null=True)),
                ('actual_price_timestamp', models.DateTimeField(blank=True, null=True)),
                ('absolute_error', models.FloatField(blank=True, null=True)),
                ('pct_error', models.FloatField(blank=True, null=True)),
                ('direction_match', models.BooleanField(blank=True, null=True)),
                ('results_json', models.JSONField(blank=True, default=dict)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='single_stock_forecasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
    ]
